### ISSUE TITLE
Bug: VIP/Private Server Links Starting With a Zero are Unaccessible

### ISSUE THREAD

**Issue by BoogieHasFun** [Okmada/ReTwisted#2]
whilst trying to use this program, i discovered that upon using the private server code "privateServerLinkCode=02490407503923744541237544496181" i would be met with a "no access to join this server" error. i found out that if you have a private server code that begins with a zero the zero would simply get removed entirely, as in the .config.json file it does not allow a 0 to be the first number for the server property (i think it's property, i forgot really because i haven't programmed in a while)

### with a zero:
![Screenshot 2024-04-24 191742](https://github.com/Okmada/ReTwisted/assets/76754631/570c5a57-6c0b-4464-b845-b2d4fdb7a5b3)

### without a zero:
![Screenshot 2024-04-24 191912](https://github.com/Okmada/ReTwisted/assets/76754631/9b228fed-4530-41ce-9501-e781218bf3f2)

### along with further evidence that the 0 is being removed by the program:
![Screenshot 2024-04-24 192617](https://github.com/Okmada/ReTwisted/assets/76754631/e12efbf4-ba46-4f10-bd4f-3872badd5057)
<br> ![Screenshot 2024-04-24 192708](https://github.com/Okmada/ReTwisted/assets/76754631/c0d9f5a5-0460-4525-8da5-89fffc51437c)

also, sorry for a second issue and have a nice day

**Comment by Okmada** [comment]
Fixed in commit [341e51a](https://github.com/Okmada/ReTwisted/commit/341e51a7d13e38a0079591f4f94d4e470d595dcf)
