### ISSUE TITLE
Needs to be updated for the new 1.21 GUI

### ISSUE THREAD

**Issue by BoogieHasFun** [Okmada/ReTwisted#3]
the 1.21 update not only has removed LITE mode, but also has a new GUI. thankfully, this might not be very hard to fix. 

1.21 new GUI ex. <br>
![Screenshot 2024-05-05 004322](https://github.com/Okmada/ReTwisted/assets/76754631/6a702097-cb0e-4aa6-b467-53629552be07)

**Comment by Okmada** [comment]
Fixed in commit [5220a2a](https://github.com/Okmada/ReTwisted/commit/5220a2ae2b80311de0424493fca6e1bcf9293153)
